name = "OrthogonalLeastSquares"
uuid = "f56bffd1-a4e8-4a14-bd84-13e31dd27f12"
authors = ["Robert Rudolph <rudolph.consulting@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
